services:
    reverseproxy:
        image: reverse_proxy
        ports:
            - 8080:8080
            - 8081:8081
        restart: always

    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always

    apache:
        depends_on:
            - reverseproxy
        image: httpd:alpine
        restart: always
